services:
- type: pserv
  name: rodeobot
  env: node
  plan: starter
  pullRequestPreviewsEnabled: true
  buildCommand: npm install
  startCommand: npm start
  healthCheckPath: /healthz
  envVars:
    - key: TOKEN
      sync: false