services:
- type: pserv
  name: rodeobot
  env: node
  plan: starter
  pullRequestPreviewsEnabled: true
  buildCommand: npm install && npm run deploy-commands
  startCommand: npm start
  envVars:
    - fromGroup: rodeobot-secrets
  disk:
      name: sqlite-data
      mountPath: /db
      sizeGB: 1
envVarGroups:
- name: rodeobot-secrets
  envVars:
  - key: DISCORD_KEY
    sync: false
  - key: GIPHY_KEY
    sync: false
  - key: GENERAL_CHANNEL_ID
    sync: false
  - key: DB_PATH
    value: /db/rodeo.db