services:
- type: pserv
  name: rodeobot
  env: node
  plan: starter
  pullRequestPreviewsEnabled: true
  buildCommand: npm install && npm run deploy-commands
  startCommand: npm start
  healthCheckPath: /healthz
  envVars:
    - fromGroup: rodeobot-secrets
  disk:
      name: sqlite-data
      mountPath: /db
      sizeGB: 1
- type: cron
  name: rodeobot-scheduled
  env: node
  schedule: "0 * * * *"
  buildCommand: npm install
  startCommand: npm run scheduled
  envVars:
    - fromGroup: rodeobot-secrets
envVarGroups:
- name: rodeobot-secrets
  envVars:
  - key: DISCORD_KEY
    sync: false
  - key: GIPHY_KEY
    sync: false
  - key: GENERAL_CHANNEL_ID
    sync: false