name: Birthday Bot

on:
  schedule:
    - cron: '0 22,23 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual trigger'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    
    - name: Debug - Display Node.js and npm versions
      run: |
        node --version
        npm --version
    
    - name: Install dependencies
      run: npm ci
      
    - name: Create friends.json from secret
      env:
        FRIENDS_JSON: ${{ secrets.FRIENDS_JSON }}
      run: |
        node -e "
          const fs = require('fs');
          const friendsData = process.env.FRIENDS_JSON;
          console.log('Secret length:', friendsData.length);
          console.log('First 10 characters:', friendsData.substring(0, 10) + '...');
          try {
            const parsedData = JSON.parse(friendsData);
            console.log('JSON parsed successfully');
            console.log('Number of friends:', Object.keys(parsedData).length);
            fs.writeFileSync('friends.json', JSON.stringify(parsedData, null, 2));
            console.log('friends.json written successfully');
          } catch (error) {
            console.error('Error parsing JSON:', error.message);
          }
        "
    
    - name: Debug - Check friends.json
      run: |
        echo "Friends.json file size:"
        ls -l friends.json
        echo "First few lines of friends.json structure:"
        head -n 5 friends.json | sed 's/[^{}[],]/_/g'
    
    - name: Run Birthday Bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        GENERAL_CHANNEL_ID: ${{ secrets.GENERAL_CHANNEL_ID }}
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "Manual run triggered: ${{ github.event.inputs.reason }}"
          node index.js
        else
          if [ "$(TZ='Australia/Melbourne' date +%Z)" = "AEDT" ]; then
            if [ "$(TZ='UTC' date +%H)" = "23" ]; then
              node index.js
            fi
          else
            if [ "$(TZ='UTC' date +%H)" = "22" ]; then
              node index.js
            fi
          fi
        fi
    
    - name: Clean up friends.json
      if: always()
      run: rm friends.json
