name: Birthday Bot

on:
  schedule:
    # 23:00 UTC is 9:00 AEST (UTC+10, standard time)
    - cron: '0 23 * * *'
    # 22:00 UTC is 9:00 AEDT (UTC+11, daylight savings time)
    - cron: '0 22 * * *'
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run regardless of time'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  run-birthday-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js LTS
      uses: actions/setup-node@v3
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check Melbourne Time
      id: melbourne-time
      run: |
        # Use TZ environment variable to get Melbourne time
        current_hour=$(TZ='Australia/Melbourne' date +"%H")
        if [ "$current_hour" = "09" ]; then
          echo "is_9am=true" >> $GITHUB_OUTPUT
        else
          echo "is_9am=false" >> $GITHUB_OUTPUT
        fi
        echo "Current time in Melbourne: $(TZ='Australia/Melbourne' date)"
    
    - name: Run Birthday Bot
      if: steps.melbourne-time.outputs.is_9am == 'true' || github.event.inputs.force_run == 'true'
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        GENERAL_CHANNEL_ID: ${{ secrets.GENERAL_CHANNEL_ID }}
        FRIENDS_DATA: ${{ secrets.FRIENDS_DATA }}
      run: |
        echo "Running Birthday Bot at $(TZ='Australia/Melbourne' date)"
        echo "Node.js version: $(node -v)"
        echo "npm version: $(npm -v)"
        node index.js

    - name: Log Skipped Run
      if: steps.melbourne-time.outputs.is_9am != 'true' && github.event.inputs.force_run != 'true'
      run: echo "Skipped running Birthday Bot as it's not 9 AM in Melbourne and force run was not selected."