name: Birthday Bot

on:
  schedule:
    - cron: '0 22,23 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual trigger'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Debug - List directory contents
      run: ls -la
    
    - name: Debug - Display package.json content
      run: cat package.json || echo "package.json not found"
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Debug - Display Node.js and npm versions
      run: |
        node --version
        npm --version
    
    - name: Install dependencies
      run: |
        npm install
        npm ls --depth=0
      
    - name: Debug - List node_modules
      run: ls -la node_modules
    
    - name: Create friends.json from secret
      run: echo '${{ secrets.FRIENDS_JSON }}' > friends.json
    
    - name: Debug - Display index.js content
      run: cat index.js || echo "index.js not found"
    
    - name: Run Birthday Bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        GENERAL_CHANNEL_ID: ${{ secrets.GENERAL_CHANNEL_ID }}
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "Manual run triggered: ${{ github.event.inputs.reason }}"
          node --trace-warnings index.js
        else
          if [ "$(TZ='Australia/Melbourne' date +%Z)" = "AEDT" ]; then
            if [ "$(TZ='UTC' date +%H)" = "23" ]; then
              node --trace-warnings index.js
            fi
          else
            if [ "$(TZ='UTC' date +%H)" = "22" ]; then
              node --trace-warnings index.js
            fi
          fi
        fi
    
    - name: Clean up friends.json
      if: always()
      run: rm friends.json
